name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - master  # Or 'main' if you're using 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Jupyter Book
        run: |
          pip install jupyter-book

      - name: Build the Jupyter Book
        run: |
          jupyter-book build .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: _build/html
